# This starter workflow is for a CMake project running on a single platform and single architecture
name: CMake on x64 Debug
author: Uriel Mann

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: ./.github/workflows/cmake-base
      with:
        build-type: 'Debug'
        build-arch: 'Win32'
