# This starter workflow is for a CMake project running on a single platform and single architecture
name: CMake on x64 Debug

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: CMake base action
        uses: ./.github/actions/cmake-base/action.yml@feature/CMake+Visual-Studio
        with:
          build-type: 'Debug'
          build-arch: 'Win32'
